apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: shoppingproject.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: shopping-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopping-frontend-service
            port:
              number: 80
